server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_shop
    username: root
    password: Simform@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update